config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  root to: 'routines#index'  # トップページ（ルーティン一覧）
  resources :routines
  #get '/routines', to: 'routines#index', as: :routines  # ルーティン一覧
  #get 'routines/new', to: 'routines#new', as: :new_routine  # ルーティン新規作成
  #post 'routines', to: 'routines#create'  # ルーティン作成処理
  #get 'routines/:id', to: 'routines#show', as: :routine  # ルーティン詳細
  #delete 'routines/:id', to: 'routines#destroy'  # ルーティン削除
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/routine.rb
class Routine < ApplicationRecord
  #validates :title, presence: true
  #validates :body, presence: true, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/routines_controller.rb
class RoutinesController < ApplicationController
  def index
    @routines = Routine.all
  end

  def show
    @routine = Routine.find(params[:id])
  end

  def new
    @routine = Routine.new()
  end

  def create
    @routine = Routine.new(routine_params)

    if @routine.save
      redirect_to @routine
    else
      render :new, status: :unprocessble_entity
    end
  end

  def edit
    @routine = Routine.find(params[:id])
  end

  def update
    @routine = Routine.find(params[:id])

    if @routine.update(routine_params)
      redirect_to @routine
    else
      render :new, status: :unprocessble_entity
    end
  end

  def destroy
    @article = Routine.find(params[:id])
    @article.destroy

    redirect_to routines_path, status: :see_other
  end

  private
    def routine_params
      params.require(:routine).permit(:title, :counter, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/routines_helper.rb
module RoutinesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RoutineRing</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
</head>
<body>
  <%= yield %>
  <%= javascript_importmap_tags %>
</body>
</html>

app/views/routines/_form.html.erb
<%= form_with model: routine do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% routine.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :couter %><br>
    <%= form.number_field :counter %>
    <% routine.errors.full_messages_for(:counter).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :completed %><br>
    <%= form.check_box :completed %>
    <% routine.errors.full_messages_for(:completed).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/routines/_form.thml.erb
<%= form_with model: routine do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% routine.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
    <% routine.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/routines/edit.html.erb
<h1>Edit Routine</h1>

<%= render "form", routine: @routine %>

<%= link_to 'ホームへ戻る', routines_path %>

app/views/routines/index.html.erb
<h1>RoutineRing</h1>

<%= link_to 'Create New Routine', new_routine_path %><br><br>


<%= "Your Routine List" %><br>
<ul>
  <% @routines.each do |routine| %>
    <li>
      <%= link_to routine.title, routine %>
      </a>
    </li>
  <% end %>
</ul>

app/views/routines/new.html.erb
<h1>Create New Routine</h1>
<!-- ルーティン作成フォーム -->
<%= link_to 'ホームへ戻る', routines_path %>

app/views/routines/routines.html.erb
<h1>RoutineRing</h1>
<%= link_to 'Create New Routine', new_routine_path %>
<!-- ルーティンの一覧表示 -->

app/views/routines/show.html.erb
<h1><%= "Your Routine" %></h1>

<h3><%= @routine.title %></h3>
<p><%= @routine.counter %></p>
<p><%= @routine.completed %></p>

<ul>
  <li><%= link_to "Edit", edit_routine_path(@routine) %></li>
  <li><%= link_to "Delete", routine_path(@routine), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></li>
</ul>

<%= link_to 'ホームへ戻る', routines_path %>